# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dan and Taylor
description: > # this means to ignore newlines until "baseurl:"
  Dan and Taylor: The professionals to go to when you want to learn to dance in the Bay Area.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dantaylordance.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
